version: '3'
services:
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - "80:3000"
      - "9615:9615"
    environment: 
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      
      REDIS_HOST: redis
      REDIS_PASSWORD: password
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    expose: 
      - 6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  db:
    image: "mariadb:latest"
    container_name: db
    restart: always
    ports: 
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: TEST
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf